module.exports = {
  STATE: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  TIME_ZONE: [
    "Pacific/Midway",
    "US/Samoa",
    "US/Hawaii",
    "US/Alaska",
    "US/Pacific",
    "America/Tijuana",
    "US/Arizona",
    "US/Mountain",
    "America/Chihuahua",
    "America/Mazatlan",
    "America/Mexico_City",
    "America/Monterrey",
    "Canada/Saskatchewan",
    "US/Central",
    "US/Eastern",
    "US/East-Indiana",
    "America/Bogota",
    "America/Lima",
    "America/Caracas",
    "Canada/Atlantic",
    "America/La_Paz",
    "America/Santiago",
    "Canada/Newfoundland",
    "America/Buenos_Aires",
    "Greenland",
    "Atlantic/Stanley",
    "Atlantic/Azores",
    "Atlantic/Cape_Verde",
    "Africa/Casablanca",
    "Europe/Dublin",
    "Europe/Lisbon",
    "Europe/London",
    "Africa/Monrovia",
    "Europe/Amsterdam",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Budapest",
    "Europe/Copenhagen",
    "Europe/Ljubljana",
    "Europe/Madrid",
    "Europe/Paris",
    "Europe/Prague",
    "Europe/Rome",
    "Europe/Sarajevo",
    "Europe/Skopje",
    "Europe/Stockholm",
    "Europe/Vienna",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Athens",
    "Europe/Bucharest",
    "Africa/Cairo",
    "Africa/Harare",
    "Europe/Helsinki",
    "Europe/Istanbul",
    "Asia/Jerusalem",
    "Europe/Kiev",
    "Europe/Minsk",
    "Europe/Riga",
    "Europe/Sofia",
    "Europe/Tallinn",
    "Europe/Vilnius",
    "Asia/Baghdad",
    "Asia/Kuwait",
    "Africa/Nairobi",
    "Asia/Riyadh",
    "Asia/Tehran",
    "Europe/Moscow",
    "Asia/Baku",
    "Europe/Volgograd",
    "Asia/Muscat",
    "Asia/Tbilisi",
    "Asia/Yerevan",
    "Asia/Kabul",
    "Asia/Karachi",
    "Asia/Tashkent",
    "Asia/Kolkata",
    "Asia/Kathmandu",
    "Asia/Yekaterinburg",
    "Asia/Almaty",
    "Asia/Dhaka",
    "Asia/Novosibirsk",
    "Asia/Bangkok",
    "Asia/Jakarta",
    "Asia/Krasnoyarsk",
    "Asia/Chongqing",
    "Asia/Hong_Kong",
    "Asia/Kuala_Lumpur",
    "Australia/Perth",
    "Asia/Singapore",
    "Asia/Taipei",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Irkutsk",
    "Asia/Seoul",
    "Asia/Tokyo",
    "Australia/Adelaide",
    "Australia/Darwin",
    "Asia/Yakutsk",
    "Australia/Brisbane",
    "Australia/Canberra",
    "Pacific/Guam",
    "Australia/Hobart",
    "Australia/Melbourne",
    "Pacific/Port_Moresby",
    "Australia/Sydney",
    "Asia/Vladivostok",
    "Asia/Magadan",
    "Pacific/Auckland",
    "Pacific/Fiji",
  ],

  IMAGES_DATA: [
    {
      id: 1,
      path: "/hero-section/changing-image/runner.svg",
      dimensions: { height: 776, width: 850 },
      dimensionsForLg2: { height: 650, width: 550 },
      dimensionsForXl: { height: 700, width: 650 },
      responsive: { height: 400, width: 400, left: 30 },
      position: { left: 45, bottom: "" },
    },
    {
      id: 2,
      path: "/hero-section/changing-image/female-singer-new.png",
      dimensions: { height: 500, width: 400 },
      dimensionsForLg2: { height: 300, width: 300 },
      dimensionsForXl: { height: 400, width: 350 },
      responsive: { height: 150, width: 200, left: 24 },
      position: { left: 45, bottom: "" },
    },
    {
      id: 3,
      path: "/hero-section/changing-image/basketball-player-new.png",
      dimensions: { height: 766, width: 502 },
      dimensionsForLg2: { height: 550, width: 350 },
      dimensionsForXl: { height: 600, width: 400 },
      responsive: { height: 260, width: 260, left: 45 },
      position: { left: 45, bottom: "" },
    },
    {
      id: 4,
      path: "/hero-section/changing-image/drms.svg",
      dimensions: { height: 630, width: 620 },
      dimensionsForLg2: { height: 400, width: 450 },
      dimensionsForXl: { height: 500, width: 500 },
      responsive: { height: 300, width: 400, left: 45 },
      position: { left: 45, bottom: "" },
    },
    {
      id: 5,
      path: "/hero-section/changing-image/cyclelist.svg",
      dimensions: { height: 750, width: 500 },
      dimensionsForLg2: { height: 650, width: 400 },
      dimensionsForXl: { height: 700, width: 450 },
      responsive: { height: 250, width: 250, left: 45 },
      position: { left: 45, bottom: "" },
    },
    {
      id: 6,
      path: "/hero-section/changing-image/dj-new.png",
      dimensions: { height: 1020, width: 680 },
      dimensionsForLg2: { height: 920, width: 580 },
      dimensionsForXl: { height: 1000, width: 650 },
      responsive: { height: 250, width: 450, left: 45 },
      position: { left: 45, bottom: "0" },
    },
  ],
};
