import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
